config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root to: 'homes#index'
	resources :products
	resources :companies
	resources :users
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ActiveRecord::Base

	has_many :products, foreign_key: 'companies_id', dependent: :destroy
	has_many :users, foreign_key: 'companies_id', dependent: :destroy
	validates :name, :director_name, :city, presence: true

	def self.display_products(id)
		@product_array = Array.new
		@product_array = Product.where(:companies_id => id)
		return @product_array
	end

	def self.display_users(id)
		@users_array = Array.new
		@users_array = User.where(:companies_id => id)
		return @users_array
	end

end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/product.rb
class Product < ActiveRecord::Base

	belongs_to :company, optional: true
	attr_accessor :company
	validates :name, :quantity, :reference, presence: true

	def self.company_name(id)
		Company.find(id)
	end

	def self.show_one_product(id)
		@product = {}
		@product[:product] = Product.find(id)
		@company = Company.find(@product[:product].companies_id)
		@product[:company] = @company.name

		return @product
	end

end

app/models/user.rb
class User < ActiveRecord::Base

	belongs_to :company, optional: true, dependent: :destroy
	attr_accessor :company
	validates :last_name, :first_name, presence: true

	def self.company_name(id)
		Company.find(id)
	end

	def self.show_one_user(id)
		@user = {}
		@user[:user] = User.find(id)
		@company = Company.find(@user[:user].companies_id)
		@user[:company] = @company.name

		return @user
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	before_action :authenticate_admin!
	def index
		@companies = Company.all
	end

	def show
		@company = Company.find(params[:id])
	end

	def new
		@company = Company.new
	end

	def edit
		@company = Company.find(params[:id])
	end

	def update
		@company = Company.find(params[:id])
		@company.update(valid_params)
		redirect_to company_path
	end

	def create
		@company = Company.new(valid_params)

		respond_to do |r|
			if @company.save
				r.html { redirect_to companies_path(@company.id), notice: 'Compagnie créée' }
			else
				r.html { render :new }
			end
		end
	end

	def destroy
		@company = Company.find(params[:id])
		@company.destroy
		redirect_to companies_path
	end

	private

	def valid_params
		params.require(:company).permit(:name, :director_name, :city)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index

	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :authenticate_admin!

	def index
		@products = Product.all
	end

	def show
		@product = Product.show_one_product(params[:id])
	end

	def create
		@product = Product.new(valid_product)

		respond_to do |r|
			if @product.save
				r.html { redirect_to product_path(@product.id), notice: "Produit enregistré" }
			else
				r.html { render 'new' }
			end
		end
	end

	def new
		@product = Product.new
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
		@product.update(valid_product)
		redirect_to product_path
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to products_path
	end

	private

	def valid_product
		params.require(:product).permit(:name, :reference, :quantity, :companies_id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_admin!

	def index
		@users = User.all
	end

	def show
		@user = User.show_one_user(params[:id])
	end

	def create
		@user = User.new(users_params)

		respond_to do |r|
			if @user.save
				r.html { redirect_to user_path(@user.id) }
			else
				r.html { render new_user_path }
			end
		end
	end

	def new
		@user = User.new
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.update(users_params)
		redirect_to user_path
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to users_path
	end

	private

	def users_params
		params.require(:user).permit(:first_name, :last_name, :companies_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
	def self.products
		@product_array = Array.new

		@prod = Product.all

		@prod.each do |p|
			id         = p.id
			name       = p.name
			quantity   = p.quantity
			reference  = p.reference
			company_id = p.companies_id.to_s.html_safe
			company    = Product.company_name(company_id).name # TODO détruire les produits et user quand on kill une companie

			@tab = Product.new(:name => name, :quantity => quantity, :reference => reference, :company => company, :id => id)
			@product_array.push(@tab)
		end
		return @product_array
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def self.users
		@users_array = Array.new

		@all_users = User.all

		@all_users.each do |u|
			id         = u.id
			first_name = u.first_name
			last_name  = u.last_name
			company_id = u.companies_id.to_s.html_safe
			company    = User.company_name(company_id).name

			@array = User.new(:id => id, :first_name => first_name, :last_name => last_name, :company => company)
			@users_array.push(@array)
		end

		return @users_array
	end
end

app/views/companies/edit.html.erb
<div class="center"><%= @company.name.upcase %></div>
<%= form_with model: @company, local: true do |f| %>
  <div class="wrapper">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="wrapper">
    <%= f.label :director_name %>
    <%= f.text_field :director_name %>
  </div>

  <div class="wrapper">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="wrapper">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/companies/index.html.erb
<div class="new-item">
  <a href="<%= new_company_path %>" class="btn btn-success">Add new company</a>
</div>

<div class="big-wrapper">
  <% @companies.each do |company| %>
    <div class="wrapper">
      <div class="inner-wrapper">
        <p>NAME : <%= company.name %></p>
        <p>CITY : <%= company.city %></p>
        <p>PDG : <%= company.director_name %></p>
      </div>
      <div class="btns">
        <p>
          <%= link_to 'Show', company_path(company.id), class: 'btn btn-info' %>
        </p>
        <p>
          <%= link_to 'Edit', edit_company_path(company.id), class: 'btn btn-warning' %>
        </p>
        <p>
          <%= link_to 'Delete', company, method: :delete, data: { confirm: 'Êtes vous sur ?' },
                      class: 'btn btn-danger' %>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/companies/new.html.erb
<div class="text-center font-weight-bold title">Add new company</div>

<% if @company.errors.any? %>
  <% @company.errors.each do |name, msg| %>
    <% name = 'Director name' if name.to_s === 'director_name' %>
    <p class="text-center"><%= name %> <%= msg %></p>
  <% end %>
<% end %>

<%= form_with model: @company, local: true do |f| %>
  <div class="wrapper">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'Nom de la société' %>
  </div>

  <div class="wrapper">
    <%= f.label :director_name %>
    <%= f.text_field :director_name, placeholder: 'Nom du directeur' %>
  </div>

  <div class="wrapper">
    <%= f.label :city %>
    <%= f.text_field :city, placeholder: 'Nom de la ville' %>
  </div>

  <div class="wrapper">
    <%= f.submit :class => 'btn btn-primary', :value => 'Enregistrer' %>
  </div>
<% end %>

app/views/companies/show.html.erb
<%
  products = Company.display_products(params[:id])
  products_length = products.length

  users = Company.display_users(params[:id])
  users_length = users.length
%>
<div class="text-center font-weight-bold title"><%= @company.name.upcase %></div>


<ul class="show">
  <li>
    <p><span class="font-weight-bold">Company name :</span> <%= @company.name %></p>
    <p><span class="font-weight-bold">Company CEO :</span> <%= @company.director_name %></p>
    <p><span class="font-weight-bold">Company city :</span> <%= @company.city %></p>

    <div class="wrapper">
      <div class="inner-wrapper">
        <%= 'This company has not product' if products_length === 0 %>
        <% if products.length > 0 %>
          <p class="text-center font-weight-bold"><%= products_length === 1 ? 'Product' : 'Products list' %></p>

          <div class="column">
            <% products.each do |p| %>
              <p class="lists">- <%= p.name %></p>
            <% end %>
          </div>

        <% end %>
      </div>

      <div class="inner-wrapper">
        <%= 'This company has not user' if users_length === 0 %>
        <% if users.length > 0 %>
        <p class="text-center font-weight-bold"><%= users_length === 1 ? 'User' : 'Users list' %></p>

          <div class="column">
            <% users.each do |u| %>
              <p class="lists">- <%= u.first_name.capitalize %> <%= u.last_name.upcase %></p>
            <% end %>
          </div>

        <% end %>
      </div>
    </div>

  </li>
  <li class="btns">
    <p><%= link_to 'Index', companies_path, class: 'btn btn-success' %></p>
    <p><%= link_to 'Edit', edit_company_path(@company.id), class: 'btn btn-warning' %></p>
    <p><%= link_to 'Delete', "/companies/#{@company.id}", method: :delete, data: { confirm: 'Êtes-vous sur ?' }, class: 'btn btn-danger' %></p>
  </li>
</ul>

app/views/homes/index.html.erb
<h1 class="center">Welcome here</h1>

<% unless admin_signed_in? %>
  <p class="center">Please click `Login` and create an account</p>
  <p class="center">Or use this account : </p>
  <p class="center">username : test@gmail.com</p>
  <p class="center">password : azerty</p>
<% end %>

<% if admin_signed_in? %>
  <div style="margin: 50px auto; display: table;" >
    <h2 class="text-center">Ruby on Rails test</h2>

    <p>
      <strong>Your database should have 3 tables (attributes are up to you) :</strong>
      Company User Product
    </p>

    <p>Company has many users Company has many products</p>

    <p>Seed file to create a few random companies at the beginning</p>

    <p>
      <strong>Forms: </strong><br />
      Form to sign up for a company Form to create a product belonging to a company (once signed in)
    </p>

    <p>
      <strong>Pages: </strong><br />
      Pages for the 2 forms above
    </p>

    <p>See a list of all companies : /companies</p>

    <p>See a list of all products : /products</p>

    <p>
      Additional information and expected behavior:
      => When destroying a company, all users and products are destroyed
    </p>

    <p>=> Scaffolding is forbidden</p>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>RubyOnRailsScalia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <!-- <p class="notice"><%#= notice %></p> -->
  <!-- <p class="alert"><%#= alert %></p> -->

    <%= render partial: 'partials/navigation' %>

    <% flash.each do |name, msg| %>
      <p class="text-center">
        <%= msg %>
      </p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/partials/_navigation.html.erb
<header>
  <nav>
    <ul>
      <li>
        <%= link_to 'Home', root_path %>
      </li>
      <li>
        <%= link_to 'New company', new_company_path %>
      </li>
      <li>
        <%= link_to 'New product', new_product_path %>
      </li>
      <li>
        <%= link_to 'New user', new_user_path %>
      </li>
      <li>
        <%= link_to 'All companies', companies_path %>
      </li>
      <li>
        <%= link_to 'All products', products_path %>
      </li>
      <li>
        <%= link_to 'All users', users_path %>
      </li>
      <li>
        <% if admin_signed_in? %>
          <%= link_to 'Logout', destroy_admin_session_path, method: :delete %>
        <% else %>
          <%= link_to 'Login', new_admin_session_path %>
        <% end %>
      </li>
    </ul>
  </nav>
</header>

app/views/products/edit.html.erb
<div class="center"><%= @product.name %></div>
<%= form_with model: @product, local: true do |f| %>
  <div class="wrapper">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="wrapper">
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
  </div>

  <div class="wrapper">
    <%= f.label :reference %>
    <%= f.number_field :reference %>
  </div>

  <div class="wrapper">
    <%= f.label :companies_id %>
    <%= f.select :companies_id, Company.all.collect { |c| [ c.name, c.id ] } %>
  </div>

  <div class="wrapper">
    <%= f.submit :value => 'Modifier', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/products/index.html.erb
<% @products = ProductsHelper.products %>
<div class="new-item">
  <%= link_to 'Ajouter un produit', new_product_path, class: 'btn btn-success' %>
</div>

<div class="big-wrapper">
  <% @products.each do |product| %>
    <div class="wrapper">
      <div class="inner-wrapper">
        <p><span>NAME :</span> <%= product.name %></p>
        <p><span>QUANTITY :</span> <%= product.quantity %></p>
        <p><span>REFERENCE :</span> <%= product.reference %></p>
        <p><span>COMPANY :</span> <%= product.company %></p>
      </div>
      <div class="btns">
        <p>
          <%= link_to 'Show', product_path(product.id), class: 'btn btn-info' %>
        </p>
        <p>
          <%= link_to 'Edit', edit_product_path(product.id), class: 'btn btn-warning' %>
        </p>
        <p>
          <%= link_to 'Delete', "products/#{product.id}", method: :delete, data: { confirm: 'Êtes vous sur ?' },
                      class: 'btn btn-danger' %>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<div class="text-center font-weight-bold title">Add new product</div>

<% if @product.errors.any? %>
  <% @product.errors.each do |name, msg| %>
    <p class="text-center"><%= name %> <%= msg %></p>
  <% end %>
<% end %>

<%= form_with model: @product, local: true do |f| %>
  <div class="wrapper">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'Nom du produit' %>
  </div>

  <div class="wrapper">
    <%= f.label :reference %>
    <%= f.number_field :reference, placeholder: 'Référence du produit' %>
  </div>

  <div class="wrapper">
    <%= f.label :quantity %>
    <%= f.number_field :quantity, placeholder: 'Quantité' %>
  </div>

  <div class="wrapper">
    <%= f.label :companies_id %>
    <%= f.select :companies_id, Company.all.collect { |c| [ c.name, c.id ] } %>
  </div>

  <div class="wrapper">
    <%= f.submit :class => 'btn btn-primary', :value => 'Enregistrer' %>
  </div>
<% end %>

app/views/products/show.html.erb
<div class="text-center font-weight-bold title"><%= @product[:product].name.upcase %></div>

<ul class="show">
  <li>
    <p><span class="font-weight-bold">Product name : </span><%= @product[:product].name %></p>
    <p><span class="font-weight-bold">Product quantity : </span><%= @product[:product].quantity %></p>
    <p><span class="font-weight-bold">Product reference : </span><%= @product[:product].reference %></p>
    <p><span class="font-weight-bold">Belongs to company : </span><%= @product[:company] %></p>
  </li>
  <li class="btns">
    <p><%= link_to 'Retour index', products_path, class: 'btn btn-success' %></p>
    <p><%= link_to 'Edit', edit_product_path(@product[:product].id), class: 'btn btn-warning' %></p>
    <p><%= link_to 'Delete', "/products/#{@product[:product].id}", method: :delete, data: { confirm: 'Êtes-vous sur ?' }, class: 'btn btn-danger' %></p>
  </li>
</ul>

app/views/users/edit.html.erb
<div class="center font-weight-bold"><%= @user.first_name.capitalize %> <%= @user.last_name.upcase %></div>
<%= form_with model: @user, local: true do |f| %>
  <div class="wrapper">
    <%= f.label :fist_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="wrapper">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="wrapper">
    <%= f.label :companies_id %>
    <%= f.select :companies_id, Company.all.collect { |c| [ c.name, c.id ] } %>
  </div>

  <div class="wrapper">
    <%= f.submit :value => 'Modifier', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/index.html.erb
<% @users = UsersHelper.users %>

<div class="new-item">
  <%= link_to 'Ajouter un utilisateur', new_user_path, class: 'btn btn-success' %>
</div>

<div class="big-wrapper">
  <% @users.each do |user| %>
    <div class="wrapper">
      <p>FIRST_NAME : <%= user.first_name %></p>
      <p>LAST_NAME : <%= user.last_name %></p>
      <p>COMPANY : <%= user.company %></p>
      <div class="btns">
        <p>
          <%= link_to 'Show', user_path(user.id), class: 'btn btn-info' %>
        </p>
        <p>
          <%= link_to 'Edit', edit_user_path(user.id), class: 'btn btn-warning' %>
        </p>
        <p>
          <%= link_to 'Delete', "users/#{user.id}", method: :delete, data: { confirm: 'Êtes-vous sur ?' },
                      class: 'btn btn-danger' %>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="text-center font-weight-bold title">Add new user</div>

<%= form_with model: @user do |f| %>
  <div class="wrapper">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, placeholder: 'Prénom' %>
  </div>

  <div class="wrapper">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, placeholder: 'Nom de famille' %>
  </div>

  <div class="wrapper">
    <%= f.label :companies_id %>
    <%= f.select :companies_id, Company.all.collect { |c| [ c.name, c.id ] } %>
  </div>

  <div class="wrapper">
    <%= f.submit :value => 'Enregistrer', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="text-center font-weight-bold title"><%= @user[:user].first_name.capitalize %> <%= @user[:user].last_name.upcase %></div>

<ul class="show">
  <li>
    <p><span class="font-weight-bold">User first name :</span> <%= @user[:user].first_name %></p>
    <p><span class="font-weight-bold">User last name :</span> <%= @user[:user].last_name %></p>
    <p><span class="font-weight-bold">Belongs to company :</span> <%= @user[:company] %></p>
  </li>
  <li class="btns">
    <p><%= link_to 'Index', users_path, class: 'btn btn-success' %></p>
    <p><%= link_to 'Edit', edit_user_path(@user[:user].id), class: 'btn btn-warning' %></p>
    <p><%= link_to 'Delete', "/users/#{@user[:user].id}", method: :delete, data: { confirm: 'Êtes-vous sur ?' }, class: 'btn btn-danger' %></p>
  </li>
</ul>